[2024-06-30 07:54:05,409] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-30T07:53:54.647763+00:00 [None]>
[2024-06-30 07:54:05,419] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-30T07:53:54.647763+00:00 [None]>
[2024-06-30 07:54:05,419] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 07:54:05,419] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-06-30 07:54:05,420] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 07:54:05,437] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-06-30T07:53:54.647763+00:00
[2024-06-30 07:54:05,443] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-06-30T07:53:54.647763+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp2g2jlus2', '--error-file', '/tmp/tmpf35nzqbg']
[2024-06-30 07:54:05,441] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2024-06-30 07:54:05,444] {standard_task_runner.py:77} INFO - Job 4: Subtask task_zero
[2024-06-30 07:54:05,482] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-06-30T07:53:54.647763+00:00 [running]> on host 2532fdaf14cb
[2024-06-30 07:54:05,523] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-06-30T07:53:54.647763+00:00
[2024-06-30 07:54:05,525] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-06-30 07:54:05,526] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-06-30 07:54:05,535] {subprocess.py:75} INFO - Output:
[2024-06-30 07:54:06,241] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-06-30 07:54:06,302] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-06-30 07:54:06,310] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-06-30 07:54:09,753] {subprocess.py:83} INFO - Command exited with return code 0
[2024-06-30 07:54:09,777] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20240630T075354, start_date=20240630T075405, end_date=20240630T075409
[2024-06-30 07:54:09,828] {local_task_job.py:151} INFO - Task exited with return code 1
