[2024-06-30 07:54:55,386] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 07:54:55,395] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 07:54:55,396] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 07:54:55,396] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-06-30 07:54:55,396] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 07:54:55,407] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-06-29T00:00:00+00:00
[2024-06-30 07:54:55,409] {standard_task_runner.py:52} INFO - Started process 332 to run task
[2024-06-30 07:54:55,411] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-06-29T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpdcdek75e', '--error-file', '/tmp/tmpc1dmhop4']
[2024-06-30 07:54:55,412] {standard_task_runner.py:77} INFO - Job 5: Subtask task_zero
[2024-06-30 07:54:55,440] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-06-29T00:00:00+00:00 [running]> on host 2532fdaf14cb
[2024-06-30 07:54:55,478] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-06-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-29T00:00:00+00:00
[2024-06-30 07:54:55,479] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-06-30 07:54:55,480] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-06-30 07:54:55,485] {subprocess.py:75} INFO - Output:
[2024-06-30 07:54:56,196] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-06-30 07:54:56,252] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-06-30 07:54:56,258] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-06-30 07:54:59,763] {subprocess.py:83} INFO - Command exited with return code 0
[2024-06-30 07:54:59,788] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20240629T000000, start_date=20240630T075455, end_date=20240630T075459
[2024-06-30 07:54:59,814] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-30 07:54:59,836] {local_task_job.py:151} INFO - Task exited with return code 0
