[2024-11-27 06:28:27,829] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-30T00:00:00+00:00 [queued]>
[2024-11-27 06:28:27,846] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-06-30T00:00:00+00:00 [queued]>
[2024-11-27 06:28:27,846] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-11-27 06:28:27,846] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-11-27 06:28:27,848] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-11-27 06:28:27,868] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-06-30T00:00:00+00:00
[2024-11-27 06:28:27,872] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2024-11-27 06:28:27,881] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-06-30T00:00:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpj8qhhb1t', '--error-file', '/tmp/tmpugpjk0ht']
[2024-11-27 06:28:27,882] {standard_task_runner.py:77} INFO - Job 25: Subtask task_zero
[2024-11-27 06:28:27,939] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-06-30T00:00:00+00:00 [running]> on host 4ecec8cb0ca2
[2024-11-27 06:28:27,994] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-06-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-30T00:00:00+00:00
[2024-11-27 06:28:27,995] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-11-27 06:28:27,997] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-11-27 06:28:28,003] {subprocess.py:75} INFO - Output:
[2024-11-27 06:28:29,107] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-11-27 06:28:29,220] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-11-27 06:28:29,227] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-11-27 06:28:33,510] {subprocess.py:83} INFO - Command exited with return code 0
[2024-11-27 06:28:33,550] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20240630T000000, start_date=20241127T062827, end_date=20241127T062833
[2024-11-27 06:28:33,590] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-27 06:28:33,617] {local_task_job.py:151} INFO - Task exited with return code 0
